import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SuperAdminDashboard from "@/pages/SuperAdmin-page/components/dashbordLayout";
import { Montserrat } from "next/font/google";
import { Footer } from "@/components/Footer";
import { StoreProvider } from "@/lib/redux/storeProvider";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${montserrat.className} antialiased`}>
          <SuperAdminDashboard>
            {children}
          </SuperAdminDashboard>
        </body>
      </html>
    </StoreProvider>
  );
}
